In [1]:
# 1D ARRAY
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(a[::2])
print(a[0])
print(a[-1])
print(a[2:4])
print(a[-2:-4:-1])
a.ndim

[1 2 3 4 5]
[1 3 5]
1
5
[3 4]
[4 3]


1

In [2]:
# 2D ARRAY
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b[0])
b.ndim
print(b[0:2,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[1 2]
 [4 5]]


In [3]:
#reshape
#generate random array
#condition
#concatenation

In [4]:
#condition
d=np.array([1,2,3,4,5,6])
d[d>3]

array([4, 5, 6])

In [5]:
d>3

array([False, False, False,  True,  True,  True])

In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
p = np.concatenate((a,b),axis=0)
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#unique value
np.unique(d)
#no of counts of each unique value
np.unique(d,return_counts=True)
#or we can use bincount

(array([1, 2, 3, 4, 5, 6]), array([1, 1, 1, 1, 1, 1], dtype=int64))

In [36]:
#np.where
x=np.array([1,4,5,2,5,6])
y=np.array([1,2,3,4,5,6,7,8,9])
np.where(x==y)

C:\Users\devu0\AppData\Local\Temp\ipykernel_8168\2027117449.py:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.where(x==y)


(array([], dtype=int64),)

In [9]:
np.where(a<4)

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))

In [10]:
#matrix multipliction
a=np.arange(1,5).reshape(2,2)
print(a)
b=np.arange(1,7).reshape(2,3)
print(b)
#no of row in 1 must be = to columns in 2
#np.tranpose
print(np.matmul(a,b))
a.shape

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]
[[ 9 12 15]
 [19 26 33]]


(2, 2)

In [11]:
#mean median
np.mean(a)
np.median(a)

2.5

In [12]:
#generate random values
np.random.randint(1,10,(2,2))
#uniform
np.random.uniform(-10.0,10.0,(3,3))
#also np.random.rand


array([[-0.86540972,  2.91591942,  1.50583939],
       [-7.97081356, -8.30597652,  6.03178661],
       [-3.90877058, -1.37489123,  3.4399915 ]])

In [19]:
#linspace
z= np.linspace(0,1,50, endpoint=False)
z
#endpoint is optional

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98])

In [24]:
#shuffle
np.random.shuffle(z)
z

array([0.72, 0.16, 0.32, 0.1 , 0.06, 0.02, 0.98, 0.6 , 0.74, 0.84, 0.88,
       0.66, 0.36, 0.92, 0.8 , 0.58, 0.68, 0.34, 0.3 , 0.18, 0.12, 0.76,
       0.44, 0.48, 0.54, 0.2 , 0.5 , 0.9 , 0.  , 0.4 , 0.56, 0.08, 0.22,
       0.82, 0.14, 0.38, 0.52, 0.04, 0.96, 0.26, 0.28, 0.94, 0.86, 0.24,
       0.42, 0.46, 0.78, 0.64, 0.7 , 0.62])

In [25]:
#max
z.max()
z.min()
z.argmax #gives index number
z.argmin


0.98

In [30]:
#vstack
np.vstack((z,z))
np.hstack((d,d))

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [37]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
#sum of all elements of 
np.sum(z,axis=0)
np.sum(z[0])

0.72

In [53]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a = np.append(a,[[6],[11]],axis=1)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])